### ISSUE TITLE
Consider upgrading tslog to ^4.4.0

### ISSUE THREAD

**Issue by adiled** [skalenetwork/ima-js#50]
**Describe the bug**

`@latest: 1.1.0-custom.4`

Browser support for `tslog` version (`^3.2.0`) is broken, particularly with vite (esbuild / rollup).

As validated in admin-ui, `^4.4.0` fixes the issues: https://github.com/fullstack-build/tslog/issues/175

**Comment by dmytrotkk** [comment]
`ts-log` was replaced with `debug` library in ima-js 2.0.0

CC @adiled @cstrangedk
