### ISSUE TITLE
Migrate to ethers.js v6

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/ima-js#59]
### Problem

Our project currently uses ethers.js v5, but v6 has been released with new features and improvements that could benefit our project.

### Upgrade steps

- Update the package.json file to use ethers.js v6.
- Review the [ethers.js v6 changelog](https://github.com/ethers-io/ethers.js/releases/tag/v6.0.0) and update the project code accordingly.
- Verify the existing test suite to ensure that all tests pass after the update.
- Test the application manually to make sure that everything still works as expected.

ethers.js v6 includes several new features and improvements, migration guide: https://docs.ethers.org/v6/migrating/

This task is a part of our ongoing effort to keep our project's dependencies up-to-date and take advantage of the latest features and improvements in our tech stack.

**Comment by yatsunastya** [comment]
No QA status
